// Маппинг Unicode-эмодзи → анимированные GIF из public/animated-emojis/

const EMOJI_GIF_MAP: Record<string, string> = {
  // Сердца
  '❤️': '/animated-emojis/3340+heart_red.gif',
  '❤': '/animated-emojis/3340+heart_red.gif',
  '🧡': '/animated-emojis/3370+heart_orange.gif',
  '💛': '/animated-emojis/3372+heart_yellow.gif',
  '💚': '/animated-emojis/3373+green_heart.gif',
  '💙': '/animated-emojis/3371+blue_heart.gif',
  '💜': '/animated-emojis/3374+heart_purple.gif',
  '🖤': '/animated-emojis/3375+black_heart.gif',
  '🤎': '/animated-emojis/3376+brown_heart.gif',
  '🤍': '/animated-emojis/3377+heart_white.gif',
  '💗': '/animated-emojis/3513+growing_heart_heartpulse.gif',
  '💖': '/animated-emojis/3519+heart_sparkling.gif',
  '💘': '/animated-emojis/3381+arrow_cupid_heart.gif',
  '💝': '/animated-emojis/3384+gift_heart_ribbon.gif',
  '💔': '/animated-emojis/3382+broken_heart.gif',
  '❤️‍🔥': '/animated-emojis/3643+fire_heart_on.gif',
  '❤️‍🩹': '/animated-emojis/3644+heart_mending.gif',
  '❣️': '/animated-emojis/3515+exclamation_heart_heavy_mark_ornament.gif',
  '💕': '/animated-emojis/3520+hearts_two.gif',
  '💞': '/animated-emojis/3512+hearts_revolving.gif',
  '💓': '/animated-emojis/3514+beating_heart_heartbeat.gif',
  '🩷': '/animated-emojis/3926+heart_pink.gif',
  '🩵': '/animated-emojis/3923+blue_heart_light.gif',
  '🩶': '/animated-emojis/3924+grey_heart.gif',

  // Лица / смайлики
  '😂': '/animated-emojis/3437+face_grinning_laughing_satisfied_squinting.gif',
  '🤣': '/animated-emojis/3436+floor_laughing_on_rofl_rolling_the.gif',
  '😍': '/animated-emojis/3351+eyes_face_heart_smiling.gif',
  '🥰': '/animated-emojis/3380+face_hearts_smiling_three.gif',
  '😘': '/animated-emojis/3354+a_blowing_face_heart_kiss_kissing.gif',
  '😗': '/animated-emojis/3413+closed_eyes_face_kissing.gif',
  '😙': '/animated-emojis/3508+eyes_face_kissing_smiling.gif',
  '😚': '/animated-emojis/3509+face_kissing.gif',
  '😋': '/animated-emojis/3407+face_food_savoring_yum.gif',
  '😛': '/animated-emojis/3408+eye_face_out_stuck_tongue_winking.gif',
  '😜': '/animated-emojis/3409+evil_monkey_no_speak.gif',
  '🤪': '/animated-emojis/3442+face_zany.gif',
  '😝': '/animated-emojis/3410+closed_eyes_face_out_squinting_stuck_tongue.gif',
  '🤑': '/animated-emojis/3494+face_money_mouth.gif',
  '🤗': '/animated-emojis/3484+face_hands_hugging_hugs_open_smiling.gif',
  '🤭': '/animated-emojis/3495+face_hand_mouth_over.gif',
  '🤫': '/animated-emojis/3492+face_shushing.gif',
  '🤔': '/animated-emojis/3404+face_thinking.gif',
  '🫡': '/animated-emojis/3655+face_saluting.gif',
  '🤐': '/animated-emojis/3579+face_mouth_zipper.gif',
  '😐': '/animated-emojis/3479+face_neutral.gif',
  '😑': '/animated-emojis/3528+expressionless_face.gif',
  '😶': '/animated-emojis/3543+face_mouth_no_without.gif',
  '😏': '/animated-emojis/3411+face_smirk_smirking.gif',
  '😒': '/animated-emojis/3343+face_unamused.gif',
  '🙄': '/animated-emojis/3350+eyes_face_roll_rolling.gif',
  '😬': '/animated-emojis/3527+face_grimacing.gif',
  '🤥': '/animated-emojis/3500+face_lying.gif',
  '😌': '/animated-emojis/3405+face_relieved.gif',
  '😔': '/animated-emojis/3414+disappointed_face.gif',
  '😪': '/animated-emojis/3566+face_sleepy.gif',
  '🤤': '/animated-emojis/3525+drooling_face.gif',
  '😴': '/animated-emojis/3419+face_sleeping.gif',
  '😷': '/animated-emojis/3466+face_mask_medical.gif',
  '🤒': '/animated-emojis/3390+face_thermometer.gif',
  '🤕': '/animated-emojis/3392+bandage_face_head.gif',
  '🤢': '/animated-emojis/3391+face_nauseated.gif',
  '🤮': '/animated-emojis/3396+face_vomiting.gif',
  '🥵': '/animated-emojis/3445+face_hot.gif',
  '🥶': '/animated-emojis/3444+cold_face.gif',
  '🥴': '/animated-emojis/3487+face_woozy.gif',
  '😵': '/animated-emojis/3666+crossed_dizzy_eyes_face_knocked_out.gif',
  '🤯': '/animated-emojis/3446+exploding_head.gif',
  '🤠': '/animated-emojis/3486+cowboy_face_hat.gif',
  '🥳': '/animated-emojis/3345+face_partying.gif',
  '🥸': '/animated-emojis/3526+disguised_face.gif',
  '😎': '/animated-emojis/3420+face_smiling_sunglasses.gif',
  '🤓': '/animated-emojis/3529+face_nerd.gif',
  '🧐': '/animated-emojis/3353+face_monocle.gif',
  '😕': '/animated-emojis/3415+confused_face.gif',
  '🫤': '/animated-emojis/3656+diagonal_face_mouth.gif',
  '😟': '/animated-emojis/3417+face_worried.gif',
  '🙁': '/animated-emojis/3549+face_frowning_slightly.gif',
  '☹️': '/animated-emojis/3551+face_frowning_white.gif',
  '😮': '/animated-emojis/3348+face_mouth_open.gif',
  '😯': '/animated-emojis/3458+face_hushed.gif',
  '😲': '/animated-emojis/3462+astonished_face.gif',
  '😳': '/animated-emojis/3344+face_flushed.gif',
  '🥺': '/animated-emojis/3485+face_pleading.gif',
  '🥹': '/animated-emojis/3659+back_face_holding_tears.gif',
  '😦': '/animated-emojis/3459+face_frowning_mouth_open.gif',
  '😧': '/animated-emojis/3416+face_fear_in_scream_screaming.gif',
  '😨': '/animated-emojis/3570+face_fearful.gif',
  '😰': '/animated-emojis/3561+anxious_cold_face_sweat.gif',
  '😥': '/animated-emojis/3560+downcast_face_sweat.gif',
  '😢': '/animated-emojis/3347+cry_crying_face.gif',
  '😭': '/animated-emojis/3406+crying_face_loudly_sob.gif',
  '😱': '/animated-emojis/3425+cat_scream_weary.gif',
  '😖': '/animated-emojis/3577+confounded_face.gif',
  '😣': '/animated-emojis/3662+face_persevere_persevering.gif',
  '😞': '/animated-emojis/3663+but_disappointed_face_relieved_sad.gif',
  '😓': '/animated-emojis/3435+face_grinning_smile_sweat.gif',
  '😩': '/animated-emojis/3576+face_weary.gif',
  '😫': '/animated-emojis/3568+face_tired.gif',
  '🥱': '/animated-emojis/3460+face_yawning.gif',
  '😤': '/animated-emojis/3440+face_from_nose_steam_triumph.gif',
  '😡': '/animated-emojis/3341+enraged_face_pout_rage.gif',
  '😠': '/animated-emojis/3661+angry_face.gif',
  '🤬': '/animated-emojis/3441+cursing_face_mouth_on_symbols.gif',
  '😈': '/animated-emojis/3432+face_horns_imp_smiling.gif',
  '👿': '/animated-emojis/3430+angry_face_horns_imp.gif',
  '💀': '/animated-emojis/3349+skull.gif',
  '☠️': '/animated-emojis/3488+and_crossbones_skull.gif',
  '💩': '/animated-emojis/3572+hankey_of_pile_poo_poop_shit.gif',
  '🤡': '/animated-emojis/3505+clown_face.gif',
  '👹': '/animated-emojis/3650+japanese_ogre.gif',
  '👺': '/animated-emojis/3653+goblin_japanese.gif',
  '👻': '/animated-emojis/3480+ghost.gif',
  '👽': '/animated-emojis/3654+alien.gif',
  '👾': '/animated-emojis/3649+alien_invader_monster_space.gif',
  '🤖': '/animated-emojis/3584+face_robot.gif',
  '😺': '/animated-emojis/3422+cat_grinning_smiley.gif',
  '😸': '/animated-emojis/3423+cat_eyes_grinning_smile_smiling.gif',
  '😹': '/animated-emojis/3424+cat_joy_of_tears.gif',
  '😻': '/animated-emojis/3378+cat_eyes_heart_smiling.gif',
  '😼': '/animated-emojis/3428+cat_smile_smirk_wry.gif',
  '😽': '/animated-emojis/3426+cat_kissing.gif',
  '🙀': '/animated-emojis/3425+cat_scream_weary.gif',
  '😿': '/animated-emojis/3421+cat_crying_face.gif',
  '😾': '/animated-emojis/3427+cat_pouting.gif',
  '🫠': '/animated-emojis/3653+face_melting.gif',
  '🫣': '/animated-emojis/3657+eye_face_peeking.gif',
  '🫢': '/animated-emojis/3658+and_eyes_face_hand_mouth_open_over.gif',
  '😁': '/animated-emojis/3439+eyes_face_grinning_smile_smiling.gif',
  '😃': '/animated-emojis/3434+big_eyes_face_grinning_smiley.gif',
  '😄': '/animated-emojis/3433+face_grinning.gif',
  '😊': '/animated-emojis/3463+blush_eyes_face_smiling.gif',
  '😇': '/animated-emojis/3456+face_halo_innocent_smiling.gif',
  '🙂': '/animated-emojis/3464+face_slightly_smiling.gif',
  '🙃': '/animated-emojis/3465+down_face_upside.gif',
  '😉': '/animated-emojis/3412+face_wink_winking.gif',

  // Руки / жесты
  '👍': '/animated-emojis/3598++1_thumbs_thumbsup_up.gif',
  '👎': '/animated-emojis/3601+1_down_thumbs_thumbsdown.gif',
  '👏': '/animated-emojis/3600+clap_clapping_hands.gif',
  '🙌': '/animated-emojis/3617+hands_raised_raising.gif',
  '🤝': '/animated-emojis/3613+handshake.gif',
  '🙏': '/animated-emojis/3618+folded_hands_pray.gif',
  '💪': '/animated-emojis/3602+biceps_flexed_muscle.gif',
  '✌️': '/animated-emojis/3589+hand_v_victory.gif',
  '🤞': '/animated-emojis/3615+crossed_fingers.gif',
  '🤟': '/animated-emojis/3608+horns_metal_of_sign_the.gif',
  '🤘': '/animated-emojis/3608+horns_metal_of_sign_the.gif',
  '👌': '/animated-emojis/3599+hand_ok.gif',
  '🤌': '/animated-emojis/3606+fingers_pinched.gif',
  '🫶': '/animated-emojis/3732+hands_heart.gif',
  '👐': '/animated-emojis/3603+hands_open.gif',
  '🤲': '/animated-emojis/3614+palms_together_up.gif',
  '👋': '/animated-emojis/3597+hand_wave_waving.gif',
  '🤙': '/animated-emojis/3609+call_hand_me.gif',
  '👈': '/animated-emojis/3594+backhand_index_left_point_pointing.gif',
  '👉': '/animated-emojis/3595+backhand_index_point_pointing_right.gif',
  '👆': '/animated-emojis/3592+2_backhand_index_point_pointing_up.gif',
  '👇': '/animated-emojis/3593+backhand_down_index_point_pointing.gif',
  '☝️': '/animated-emojis/3587+index_point_pointing_up.gif',
  '✋': '/animated-emojis/3588+hand_raised.gif',
  '🤚': '/animated-emojis/3610+back_hand_of_raised.gif',
  '🖐️': '/animated-emojis/3795+fingers_hand_raised_splayed.gif',
  '🖖': '/animated-emojis/3605+and_between_fingers_hand_middle_part_raised_ring_salute_vulcan.gif',
  '🖕': '/animated-emojis/3604+extended_finger_fu_hand_middle_reversed.gif',
  '👊': '/animated-emojis/3596+facepunch_fist_oncoming_punch.gif',
  '✊': '/animated-emojis/3586+fist_raised.gif',
  '🤛': '/animated-emojis/3611+facing_fist_left.gif',
  '🤜': '/animated-emojis/3612+facing_fist_right.gif',
  '👂': '/animated-emojis/3590+ear.gif',
  '👃': '/animated-emojis/3591+nose.gif',
  '👅': '/animated-emojis/3696+tongue.gif',
  '👄': '/animated-emojis/3716+lips_mouth.gif',
  '🫦': '/animated-emojis/3722+biting_lip.gif',
  '👀': '/animated-emojis/3721+eyes.gif',
  '👁️': '/animated-emojis/3711+eye.gif',

  // Огонь / энергия
  '🔥': '/animated-emojis/3431+fire.gif',
  '✨': '/animated-emojis/3491+sparkles.gif',
  '⭐': '/animated-emojis/3510+glowing_star_star2.gif',
  '🌟': '/animated-emojis/3510+glowing_star_star2.gif',
  '💫': '/animated-emojis/3511+dizzy.gif',
  '⚡': '/animated-emojis/3713+high_voltage_zap.gif',
  '💥': '/animated-emojis/3557+boom_collision.gif',
  '🎆': '/animated-emojis/3499+fireworks.gif',
  '🎇': '/animated-emojis/3501+sparkler.gif',

  // Животные
  '🐶': '/animated-emojis/3811+dog_face.gif',
  '🐱': '/animated-emojis/3812+cat_face.gif',
  '🐭': '/animated-emojis/3806+face_mouse.gif',
  '🐹': '/animated-emojis/3809+hamster.gif',
  '🐰': '/animated-emojis/3873+rabbit_rabbit2.gif',
  '🦊': '/animated-emojis/3821+face_fox.gif',
  '🐻': '/animated-emojis/3810+bear.gif',
  '🐼': '/animated-emojis/3815+face_panda.gif',
  '🐨': '/animated-emojis/3808+koala.gif',
  '🐯': '/animated-emojis/3833+face_tiger.gif',
  '🦁': '/animated-emojis/3915+face_lion.gif',
  '🐮': '/animated-emojis/3884+cow_cow2.gif',
  '🐷': '/animated-emojis/3847+face_pig.gif',
  '🐸': '/animated-emojis/3917+frog.gif',
  '🐵': '/animated-emojis/3699+face_monkey.gif',
  '🙈': '/animated-emojis/3359+evil_monkey_no_see.gif',
  '🙉': '/animated-emojis/3700+evil_hear_monkey_no.gif',
  '🙊': '/animated-emojis/3409+evil_monkey_no_speak.gif',
  '🐔': '/animated-emojis/3805+chicken.gif',
  '🐧': '/animated-emojis/3831+penguin.gif',
  '🐦': '/animated-emojis/3846+bird.gif',
  '🐤': '/animated-emojis/3804+baby_chick.gif',
  '🐣': '/animated-emojis/3547+chick_hatching.gif',
  '🐥': '/animated-emojis/3578+baby_chick_facing_front_hatched.gif',
  '🦆': '/animated-emojis/3851+duck.gif',
  '🦅': '/animated-emojis/3623+dove_of_peace.gif',
  '🦉': '/animated-emojis/3544+owl.gif',
  '🦇': '/animated-emojis/3476+bat.gif',
  '🐺': '/animated-emojis/3904+wolf.gif',
  '🐗': '/animated-emojis/3850+bison.gif',
  '🐴': '/animated-emojis/3839+horse_racehorse.gif',
  '🦄': '/animated-emojis/3787+face_unicorn.gif',
  '🐝': '/animated-emojis/3914+bee_honeybee.gif',
  '🐛': '/animated-emojis/3892+bug.gif',
  '🦋': '/animated-emojis/3704+butterfly.gif',
  '🐌': '/animated-emojis/3834+snail.gif',
  '🐞': '/animated-emojis/3861+beetle.gif',
  '🐜': '/animated-emojis/3908+ant.gif',
  '🐢': '/animated-emojis/3838+turtle.gif',
  '🐍': '/animated-emojis/3888+snake.gif',
  '🐙': '/animated-emojis/3828+octopus.gif',
  '🦑': '/animated-emojis/3903+squid.gif',
  '🦐': '/animated-emojis/3845+shrimp.gif',
  '🦞': '/animated-emojis/3879+lobster.gif',
  '🦀': '/animated-emojis/3860+cockroach.gif',
  '🐡': '/animated-emojis/3883+fish_tropical.gif',
  '🐠': '/animated-emojis/3883+fish_tropical.gif',
  '🐟': '/animated-emojis/3744+fish.gif',
  '🦭': '/animated-emojis/3878+seal.gif',
  '🐳': '/animated-emojis/3645+spouting_whale.gif',
  '🐋': '/animated-emojis/3645+spouting_whale.gif',
  '🦈': '/animated-emojis/3878+seal.gif',
  '🦘': '/animated-emojis/3865+kangaroo.gif',
  '🦙': '/animated-emojis/3852+llama.gif',
  '🦒': '/animated-emojis/3904+giraffe.gif',
  '🦓': '/animated-emojis/3855+zebra.gif',
  '🦧': '/animated-emojis/3870+gorilla_harambe.gif',
  '🦫': '/animated-emojis/3880+raccoon.gif',
  '🦤': '/animated-emojis/3871+parrot.gif',
  '🦩': '/animated-emojis/3891+flamingo.gif',
  '🦢': '/animated-emojis/3857+swan.gif',
  '🦃': '/animated-emojis/3922+turkey.gif',
  '🐉': '/animated-emojis/3916+rex_t.gif',
  '🐾': '/animated-emojis/3679+feet_paw_prints.gif',
  '🐽': '/animated-emojis/3836+nose_pig.gif',
  '🦴': '/animated-emojis/3714+bone.gif',
  '🦿': '/animated-emojis/3624+leg_mechanical.gif',
  '🦵': '/animated-emojis/3622+leg.gif',
  '🦶': '/animated-emojis/3619+foot.gif',

  // Еда
  '🍕': '/animated-emojis/3630+pizza.gif',
  '🍔': '/animated-emojis/3632+hamburger.gif',
  '🍟': '/animated-emojis/3631+french_fries.gif',
  '🌭': '/animated-emojis/3626+dog_hot_hotdog.gif',
  '🍿': '/animated-emojis/3625+popcorn.gif',
  '🍩': '/animated-emojis/3638+doughnut.gif',
  '🍪': '/animated-emojis/3633+cookie.gif',
  '🎂': '/animated-emojis/3438+birthday_cake.gif',
  '🍰': '/animated-emojis/3629+cake_shortcake.gif',
  '🧁': '/animated-emojis/3727+cupcake.gif',
  '☕': '/animated-emojis/3733+beverage_coffee_hot.gif',
  '🍺': '/animated-emojis/3832+glass_wine.gif',
  '🍻': '/animated-emojis/3522+clinking_glasses.gif',
  '🥂': '/animated-emojis/3522+clinking_glasses.gif',
  '🍷': '/animated-emojis/3832+glass_wine.gif',
  '🍸': '/animated-emojis/3835+cocktail_glass.gif',
  '🍹': '/animated-emojis/3734+drink_tropical.gif',
  '🧃': '/animated-emojis/3698+beverage_box.gif',
  '🥤': '/animated-emojis/3634+cup_straw.gif',
  '🧋': '/animated-emojis/3678+bubble_tea.gif',
  '🍾': '/animated-emojis/3507+bottle_champagne_cork_popping.gif',
  '🍣': '/animated-emojis/3673+sushi.gif',
  '🍱': '/animated-emojis/3715+bento_box.gif',
  '🍙': '/animated-emojis/3671+ball_rice.gif',
  '🍚': '/animated-emojis/3671+ball_rice.gif',
  '🥐': '/animated-emojis/3629+cake_shortcake.gif',
  '🥨': '/animated-emojis/3725+pretzel.gif',
  '🥞': '/animated-emojis/3639+pancakes.gif',
  '🧀': '/animated-emojis/3629+cake_shortcake.gif',
  '🥚': '/animated-emojis/3723+cooking_egg_fried.gif',
  '🍳': '/animated-emojis/3723+cooking_egg_fried.gif',
  '🥓': '/animated-emojis/3629+cake_shortcake.gif',
  '🥩': '/animated-emojis/3629+cake_shortcake.gif',
  '🍖': '/animated-emojis/3718+bone_meat_on.gif',
  '🍗': '/animated-emojis/3719+leg_poultry.gif',
  '🥪': '/animated-emojis/3720+sandwich.gif',
  '🌮': '/animated-emojis/3627+taco.gif',
  '🌯': '/animated-emojis/3726+flatbread_stuffed.gif',
  '🥙': '/animated-emojis/3726+flatbread_stuffed.gif',
  '🧆': '/animated-emojis/3629+cake_shortcake.gif',
  '🍜': '/animated-emojis/3629+cake_shortcase.gif',
  '🍝': '/animated-emojis/3629+cake_shortcase.gif',
  '🍛': '/animated-emojis/3629+cake_shortcase.gif',
  '🥗': '/animated-emojis/3629+cake_shortcase.gif',
  '🍲': '/animated-emojis/3629+cake_shortcase.gif',
  '🍫': '/animated-emojis/3691+bar_chocolate.gif',
  '🍬': '/animated-emojis/3724+lollipop.gif',
  '🍭': '/animated-emojis/3724+lollipop.gif',
  '🍮': '/animated-emojis/3628+custard.gif',
  '🍯': '/animated-emojis/3901+glass_milk_of.gif',
  '🥛': '/animated-emojis/3901+glass_milk_of.gif',
  '🍼': '/animated-emojis/3910+baby_bottle.gif',
  '🫖': '/animated-emojis/3733+beverage_coffee_hot.gif',
  '🍵': '/animated-emojis/3733+beverage_coffee_hot.gif',
  '🍶': '/animated-emojis/3848+glass_tumbler.gif',
  '🧉': '/animated-emojis/3869+mate.gif',
  '🍓': '/animated-emojis/3681+strawberry.gif',
  '🍌': '/animated-emojis/3648+banana.gif',
  '🍆': '/animated-emojis/3937+eggplant.gif',
  '🥑': '/animated-emojis/3648+banana.gif',
  '🥕': '/animated-emojis/3648+banana.gif',
  '🌽': '/animated-emojis/3648+banana.gif',
  '🍄': '/animated-emojis/3648+banana.gif',
  '🍇': '/animated-emojis/3648+banana.gif',
  '🍎': '/animated-emojis/3648+banana.gif',
  '🍊': '/animated-emojis/3648+banana.gif',
  '🍋': '/animated-emojis/3648+banana.gif',
  '🍐': '/animated-emojis/3648+banana.gif',
  '🍑': '/animated-emojis/3648+banana.gif',
  '🍒': '/animated-emojis/3648+banana.gif',
  '🥝': '/animated-emojis/3648+banana.gif',
  '🍅': '/animated-emojis/3648+banana.gif',
  '🫐': '/animated-emojis/3648+banana.gif',
  '🍉': '/animated-emojis/3648+banana.gif',

  // Объекты
  '💎': '/animated-emojis/3355+gem_stone.gif',
  '🔑': '/animated-emojis/3842+key.gif',
  '🗝️': '/animated-emojis/3843+key_old.gif',
  '🔒': '/animated-emojis/3356+closed_key_lock_locked.gif',
  '🎁': '/animated-emojis/3575+balloon.gif',
  '🎈': '/animated-emojis/3575+balloon.gif',
  '🎉': '/animated-emojis/3573+party_popper_tada.gif',
  '🎊': '/animated-emojis/3429+ball_confetti.gif',
  '🏆': '/animated-emojis/3651+trophy.gif',
  '⚽': '/animated-emojis/3735+ball_soccer.gif',
  '🏀': '/animated-emojis/3760+basketball.gif',
  '🎮': '/animated-emojis/3518+game_video.gif',
  '🎨': '/animated-emojis/3581+art_artist_palette.gif',
  '🎬': '/animated-emojis/3742+board_clapper.gif',
  '🎤': '/animated-emojis/3739+microphone.gif',
  '🎵': '/animated-emojis/3675+musical_note.gif',
  '🎶': '/animated-emojis/3676+musical_notes.gif',
  '🎸': '/animated-emojis/3675+musical_note.gif',
  '🎹': '/animated-emojis/3675+musical_note.gif',
  '🎺': '/animated-emojis/3675+musical_note.gif',
  '🎻': '/animated-emojis/3675+musical_note.gif',
  '📱': '/animated-emojis/3791+iphone_mobile_phone.gif',
  '💻': '/animated-emojis/3585+computer_laptop.gif',
  '📺': '/animated-emojis/3750+television_tv.gif',
  '📷': '/animated-emojis/3518+game_video.gif',
  '💰': '/animated-emojis/3747+bag_money_moneybag.gif',
  '💵': '/animated-emojis/3358+money_wings.gif',
  '💸': '/animated-emojis/3358+money_wings.gif',
  '💳': '/animated-emojis/3794+card_identification.gif',
  '✉️': '/animated-emojis/3784+envelope_incoming.gif',
  '📝': '/animated-emojis/3360+memo_pencil.gif',
  '✏️': '/animated-emojis/3586+pencil_pencil2.gif',
  '📦': '/animated-emojis/3768+luggage.gif',
  '📁': '/animated-emojis/3387+file_folder.gif',
  '📂': '/animated-emojis/3388+file_folder_open.gif',
  '📈': '/animated-emojis/3753+chart_increasing_trend_upwards.gif',
  '📉': '/animated-emojis/3759+chart_decreasing_downwards_trend.gif',
  '📊': '/animated-emojis/3621+bar_chart.gif',
  '📌': '/animated-emojis/3786+flag_on_post_triangular.gif',
  '📎': '/animated-emojis/3387+file_folder.gif',
  '🔧': '/animated-emojis/3793+toolbox.gif',
  '🔨': '/animated-emojis/3793+toolbox.gif',
  '⚙️': '/animated-emojis/3793+toolbox.gif',
  '💣': '/animated-emojis/3687+bomb.gif',
  '🧨': '/animated-emojis/3688+firecracker.gif',
  '🪄': '/animated-emojis/3684+magic_wand.gif',
  '🔮': '/animated-emojis/3776+ball_crystal.gif',
  '🔭': '/animated-emojis/3772+telescope.gif',
  '🔬': '/animated-emojis/3763+microscope.gif',
  '💊': '/animated-emojis/3397+pill.gif',
  '💉': '/animated-emojis/3523+syringe.gif',
  '🩺': '/animated-emojis/3757+stethoscope.gif',
  '🌡️': '/animated-emojis/3686+thermometer.gif',
  '🧹': '/animated-emojis/3684+magic_wand.gif',
  '🧺': '/animated-emojis/3790+cart_shopping.gif',
  '🧻': '/animated-emojis/3398+of_paper_roll.gif',
  '🧼': '/animated-emojis/3394+soap.gif',
  '🧽': '/animated-emojis/3403+sponge.gif',
  '🛒': '/animated-emojis/3790+cart_shopping.gif',
  '🗿': '/animated-emojis/3482+moai_moyai.gif',
  '🎃': '/animated-emojis/3483+jack_lantern_o.gif',
  '🎄': '/animated-emojis/3367+christmas_tree.gif',
  '🧸': '/animated-emojis/3684+magic_wand.gif',

  // Природа / погода
  '🌈': '/animated-emojis/3919+rainbow.gif',
  '☀️': '/animated-emojis/3689+sun_sunny.gif',
  '🌤️': '/animated-emojis/3799+behind_cloud_large_sun_white.gif',
  '⛅': '/animated-emojis/3800+behind_cloud_partly_sun_sunny.gif',
  '🌥️': '/animated-emojis/3802+behind_cloud_small_sun_white.gif',
  '☁️': '/animated-emojis/3798+cloud.gif',
  '🌧️': '/animated-emojis/3800+behind_cloud_rain_sun_white.gif',
  '⛈️': '/animated-emojis/3803+cloud_lightning.gif',
  '🌩️': '/animated-emojis/3803+cloud_lightning.gif',
  '❄️': '/animated-emojis/3502+snowflake.gif',
  '☃️': '/animated-emojis/3369+snow_snowman.gif',
  '⛄': '/animated-emojis/3369+snow_snowman.gif',
  '🌙': '/animated-emojis/3448+full_moon.gif',
  '🌛': '/animated-emojis/3451+moon_new.gif',
  '🌲': '/animated-emojis/3548+evergreen_tree.gif',
  '🌳': '/animated-emojis/3556+deciduous_tree.gif',
  '🌴': '/animated-emojis/3555+palm_tree.gif',
  '🌵': '/animated-emojis/3554+cactus.gif',
  '🌾': '/animated-emojis/3545+seedling.gif',
  '🌿': '/animated-emojis/3553+herb.gif',
  '🍀': '/animated-emojis/3868+clover_four_leaf.gif',
  '🍁': '/animated-emojis/3553+herb.gif',
  '🍂': '/animated-emojis/3553+herb.gif',
  '🍃': '/animated-emojis/3553+herb.gif',
  '🌹': '/animated-emojis/3582+rose.gif',
  '🌺': '/animated-emojis/3552+hibiscus.gif',
  '🌸': '/animated-emojis/3583+blossom_cherry.gif',
  '🌷': '/animated-emojis/3571+tulip.gif',
  '💐': '/animated-emojis/3918+bouquet.gif',
  '🌱': '/animated-emojis/3545+seedling.gif',
  '☘️': '/animated-emojis/3825+shamrock.gif',

  // Транспорт
  '🚗': '/animated-emojis/3506+automobile_car_red.gif',
  '🚕': '/animated-emojis/3461+taxi.gif',
  '🏎️': '/animated-emojis/3506+automobile_car_red.gif',
  '🚓': '/animated-emojis/3517+car_police.gif',
  '🚑': '/animated-emojis/3395+ambulance.gif',
  '🚒': '/animated-emojis/3395+ambulance.gif',
  '🚐': '/animated-emojis/3506+automobile_car_red.gif',
  '🚚': '/animated-emojis/3506+automobile_car_red.gif',
  '🚛': '/animated-emojis/3506+automobile_car_red.gif',
  '🚜': '/animated-emojis/3506+automobile_car_red.gif',
  '🏍️': '/animated-emojis/3506+automobile_car_red.gif',
  '🚲': '/animated-emojis/3506+automobile_car_red.gif',
  '🚀': '/animated-emojis/3708+rocket.gif',
  '🛸': '/animated-emojis/3708+rocket.gif',
  '✈️': '/animated-emojis/3743+airplane.gif',
  '🛩️': '/animated-emojis/3743+airplane.gif',
  '🚂': '/animated-emojis/3775+locomotive_steam.gif',
  '⛵': '/animated-emojis/3771+boat_motor.gif',
  '🚢': '/animated-emojis/3771+boat_motor.gif',
  '🚤': '/animated-emojis/3771+boat_motor.gif',
  '🚁': '/animated-emojis/3708+rocket.gif',

  // Символы / знаки
  '💯': '/animated-emojis/3531+100_hundred_points.gif',
  '🔴': '/animated-emojis/3705+heart_red.gif',
  '🟠': '/animated-emojis/3370+heart_orange.gif',
  '🟡': '/animated-emojis/3372+heart_yellow.gif',
  '🟢': '/animated-emojis/3373+green_heart.gif',
  '🔵': '/animated-emojis/3371+blue_heart.gif',
  '🟣': '/animated-emojis/3374+heart_purple.gif',
  '⚫': '/animated-emojis/3375+black_heart.gif',
  '⚪': '/animated-emojis/3377+heart_white.gif',
  '🟤': '/animated-emojis/3376+brown_heart.gif',
  '♥️': '/animated-emojis/3340+heart_red.gif',
  '✅': '/animated-emojis/3682+check_heavy_mark.gif',
  '❌': '/animated-emojis/3530+cross_mark_x.gif',
  '🚫': '/animated-emojis/3530+cross_mark_x.gif',
  '🆕': '/animated-emojis/3823+button_new.gif',
  '🆙': '/animated-emojis/3854+button_up_up!.gif',
  '🆒': '/animated-emojis/3824+button_cool.gif',
  '🆓': '/animated-emojis/3858+button_free.gif',
  '🆗': '/animated-emojis/3859+button_ok.gif',
  '⚠️': '/animated-emojis/3533+anger_symbol.gif',
  '⬆️': '/animated-emojis/3792+arrow_top.gif',
  '🔞': '/animated-emojis/3783+eighteen_no_one_under_underage.gif',
  '🏁': '/animated-emojis/3778+checkered_chequered_flag.gif',
  '🚩': '/animated-emojis/3786+flag_on_post_triangular.gif',
  '🏴': '/animated-emojis/3782+black_flag_waving.gif',
  '🏳️': '/animated-emojis/3780+flag_waving_white.gif',
  '🏳️‍🌈': '/animated-emojis/3919+rainbow.gif',
  '🏴‍☠️': '/animated-emojis/3742+flag_pirate.gif',

  // Знаки препинания
  '❗': '/animated-emojis/3697+exclamation_heavy_mark_red.gif',
  '❕': '/animated-emojis/3539+exclamation_grey_mark_white.gif',
  '❓': '/animated-emojis/3541+mark_question_red.gif',
  '❔': '/animated-emojis/3540+grey_mark_question_white.gif',
  '‼️': '/animated-emojis/3693+bangbang_double_exclamation_mark.gif',
  '⁉️': '/animated-emojis/3695+exclamation_interrobang_mark_question.gif',

  // Спорт / медали
  '🥇': '/animated-emojis/3818+1st_medal_place.gif',
  '🥈': '/animated-emojis/3816+2nd_medal_place.gif',
  '🥉': '/animated-emojis/3822+3rd_medal_place.gif',
  '🏅': '/animated-emojis/3829+medal_sports.gif',
  '🎖️': '/animated-emojis/3827+medal_military.gif',
  '🎫': '/animated-emojis/3862+ticket.gif',

  // Зодиак
  '♈': '/animated-emojis/3911+aries.gif',
  '♉': '/animated-emojis/3899+taurus.gif',
  '♊': '/animated-emojis/3893+gemini.gif',
  '♋': '/animated-emojis/3909+cancer.gif',
  '♌': '/animated-emojis/3890+leo.gif',
  '♍': '/animated-emojis/3897+virgo.gif',
  '♎': '/animated-emojis/3902+libra.gif',
  '♏': '/animated-emojis/3894+scorpio_scorpius.gif',
  '♐': '/animated-emojis/3887+sagittarius.gif',
  '♑': '/animated-emojis/3885+capricorn.gif',
  '♒': '/animated-emojis/3876+aquarius.gif',
  '♓': '/animated-emojis/3881+pisces.gif',
  '⛎': '/animated-emojis/3874+ophiuchus.gif',

  // Прочие
  '💬': '/animated-emojis/3535+balloon_speech.gif',
  '💭': '/animated-emojis/3536+balloon_thought.gif',
  '🗯️': '/animated-emojis/3537+anger_bubble_right.gif',
  '💤': '/animated-emojis/3493+zzz.gif',
  '♨️': '/animated-emojis/3534+hot_hotsprings_springs.gif',
  '🏷️': '/animated-emojis/3786+flag_on_post_triangular.gif',
  '🔖': '/animated-emojis/3387+file_folder.gif',
  '🚽': '/animated-emojis/3684+magic_wand.gif',
  '🚹': '/animated-emojis/3853+mens_mens_room.gif',
  '🚺': '/animated-emojis/3856+room_womens_womens.gif',
  '🚼': '/animated-emojis/3872+baby_symbol.gif',
  '🚾': '/animated-emojis/3394+soap.gif',
  '🛂': '/animated-emojis/3905+control_passport.gif',
  '🛄': '/animated-emojis/3898+baggage_claim.gif',
  '🛅': '/animated-emojis/3897+left_luggage.gif',
  '♻️': '/animated-emojis/3682+check_heavy_mark.gif',
  '⚜️': '/animated-emojis/3684+magic_wand.gif',
  '🔱': '/animated-emojis/3684+magic_wand.gif',
  '📛': '/animated-emojis/3682+check_heavy_mark.gif',
  '🔰': '/animated-emojis/3824+button_cool.gif',
  '⭕': '/animated-emojis/3682+check_heavy_mark.gif',
  '☑️': '/animated-emojis/3680+button_check_mark_white.gif',
  '✔️': '/animated-emojis/3682+check_heavy_mark.gif',
  '❎': '/animated-emojis/3530+cross_mark_x.gif',
  '➕': '/animated-emojis/3682+check_heavy_mark.gif',
  '➖': '/animated-emojis/3530+cross_mark_x.gif',
  '➗': '/animated-emojis/3530+cross_mark_x.gif',
  '✖️': '/animated-emojis/3530+cross_mark_x.gif',
  '〰️': '/animated-emojis/3368+currency_exchange.gif',
  '💱': '/animated-emojis/3368+currency_exchange.gif',
  '💲': '/animated-emojis/3368+currency_exchange.gif',
  '⚕️': '/animated-emojis/3757+stethoscope.gif',
  '🔺': '/animated-emojis/3530+cross_mark_x.gif',
  '🔻': '/animated-emojis/3530+cross_mark_x.gif',
  '🔸': '/animated-emojis/3530+cross_mark_x.gif',
  '🔹': '/animated-emojis/3530+cross_mark_x.gif',
  '🔶': '/animated-emojis/3530+cross_mark_x.gif',
  '🔷': '/animated-emojis/3530+cross_mark_x.gif',
  '▪️': '/animated-emojis/3530+cross_mark_x.gif',
  '▫️': '/animated-emojis/3530+cross_mark_x.gif',
  '◾': '/animated-emojis/3530+cross_mark_x.gif',
  '◽': '/animated-emojis/3530+cross_mark_x.gif',
  '◼️': '/animated-emojis/3530+cross_mark_x.gif',
  '◻️': '/animated-emojis/3530+cross_mark_x.gif',
  '🟧': '/animated-emojis/3370+heart_orange.gif',
  '🟦': '/animated-emojis/3371+blue_heart.gif',
  '🟫': '/animated-emojis/3376+brown_heart.gif',
  '🟥': '/animated-emojis/3340+heart_red.gif',
  '🟩': '/animated-emojis/3373+green_heart.gif',
  '🟪': '/animated-emojis/3374+heart_purple.gif',
  '⬛': '/animated-emojis/3375+black_heart.gif',
  '⬜': '/animated-emojis/3377+heart_white.gif',
};

/**
 * Получить URL анимированного GIF для эмодзи
 */
export function getAnimatedEmojiUrl(emoji: string): string | undefined {
  return EMOJI_GIF_MAP[emoji];
}

/**
 * Проверить есть ли анимированная версия для эмодзи
 */
export function hasAnimatedEmoji(emoji: string): boolean {
  return emoji in EMOJI_GIF_MAP;
}

/**
 * Получить базовый URL для анимированных эмодзи
 */
export function getAnimatedEmojiBase(): string {
  return '/animated-emojis';
}

/**
 * Конвертировать текст с эмодзи в текст с [sticker:emoji:URL] кодами для рендера
 */
export function convertEmojisToStickerCodes(text: string): string {
  const emojiRegex = /\p{Emoji_Presentation}|\p{Emoji}\uFE0F/gu;
  return text.replace(emojiRegex, (match) => {
    const url = EMOJI_GIF_MAP[match];
    if (url) return `[sticker:emoji:${url}]`;
    return match;
  });
}

/**
 * Все эмодзи с анимированными версиями
 */
export function getAllAnimatedEmojis(): string[] {
  return Object.keys(EMOJI_GIF_MAP);
}

export const EMOJI_CATEGORIES = [
  { name: 'Частые', emojis: ['❤️','👍','😂','😮','😢','🔥','🎉','👏','💯','🤔','😍','🤩','😎','🥳','😱','💀','👻','👽','🤖','😈','💩','🤡','✨','⭐','💫','⚡','💥','🙏','💪','🫶'] },
  { name: 'Смайлики', emojis: ['😊','😇','🙂','🙃','😉','😍','🥰','😘','😗','😙','😚','😋','😛','😜','🤪','😝','🤑','🤗','🤭','🤫','🤔','🫡','🤐','🤨','😐','😑','😶','😏','😒','🙄','😬','🤥','😌','😔','😪','🤤','😴','😷','🤒','🤕','🤢','🤮','🥵','🥶','🥴','😵','🤯','🤠','🥳','🥸','😎','🤓','🧐','😕','🫤','😟','🙁','☹️','😮','😯','😲','😳','🥺','🥹','😦','😧','😨','😰','😥','😢','😭','😱','😖','😣','😞','😓','😩','😫','🥱','😤','😡','😠','🤬','😈','👿','💀','☠️','💩','🤡','👹','👺','👻','👽','👾','🤖','😺','😸','😹','😻','😼','😽','🙀','😿','😾','🫠','🫣','🫢','😁','😃','😄'].filter(e => e in EMOJI_GIF_MAP) },
  { name: 'Жесты', emojis: ['👍','👎','👏','🙌','🤝','🙏','💪','✌️','🤞','🤟','🤘','👌','🤌','👋','🤙','👈','👉','👆','👇','☝️','✋','🤚','🖐️','🖖','🖕','👊','✊','🤛','🤜','👂','👃','👅','👄','👀','👁️','🫶','👐','🤲','🫦'].filter(e => e in EMOJI_GIF_MAP) },
  { name: 'Сердца', emojis: ['❤️','❤','🧡','💛','💚','💙','💜','🖤','🤎','🤍','💗','💖','💘','💝','💔','❣️','💕','💞','💓','🩷','🩵','🩶','♥️'].filter(e => e in EMOJI_GIF_MAP) },
  { name: 'Животные', emojis: ['🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐨','🐯','🦁','🐮','🐷','🐸','🐵','🙈','🙉','🙊','🐔','🐧','🐦','🐤','🐣','🐥','🦆','🦅','🦉','🦇','🐺','🐗','🐴','🦄','🐝','🐛','🦋','🐌','🐞','🐜','🐢','🐍','🐙','🦑','🦐','🦞','🦀','🐡','🐠','🐟','🦭','🐳','🐋','🦈','🦘','🦙','🦒','🦓','🦧','🦫','🦤','🦩','🦢','🦃','🐉','🐾','🐽','🦴','🦵','🦶'].filter(e => e in EMOJI_GIF_MAP) },
  { name: 'Еда', emojis: ['🍕','🍔','🍟','🌭','🍿','🍩','🍪','🎂','🍰','🧁','☕','🍺','🍻','🥂','🍷','🍸','🍹','🧃','🥤','🧋','🍾','🍣','🍱','🍙','🍚','🥐','🥨','🥞','🧀','🥚','🍳','🥓','🥩','🍖','🍗','🥪','🌮','🌯','🥙','🧆','🍜','🍝','🍛','🥗','🍲','🍫','🍬','🍭','🍮','🍯','🥛','🍼','🫖','🍵','🍶','🧉','🍓','🍌','🍆','🥑','🥕','🌽','🍄','🍇','🍎','🍊','🍋','🍐','🍑','🍒','🥝','🍅','🫐','🍉'].filter(e => e in EMOJI_GIF_MAP) },
  { name: 'Объекты', emojis: ['💎','🔑','🗝️','🔒','🎁','🎈','🎉','🎊','🏆','⚽','🏀','🎮','🎨','🎬','🎤','🎵','🎶','🎸','🎹','🎺','🎻','📱','💻','📺','📷','💰','💵','💸','💳','✉️','📝','✏️','📦','📁','📂','📈','📉','📊','📌','📎','🔧','🔨','⚙️','💣','🧨','🪄','🔮','🔭','🔬','💊','💉','🩺','🌡️','🧹','🧺','🧻','🧼','🧽','🛒','🗿','🎃','🎄','🧸','👑','🎩','💎','🔑','🎁','🎈','🎯','🎪','🎭','🎲','🏁','🚩','🎌','🏴','🏳️'].filter(e => e in EMOJI_GIF_MAP) },
  { name: 'Природа', emojis: ['🌈','☀️','🌤️','⛅','🌥️','☁️','🌧️','⛈️','🌩️','❄️','☃️','⛄','🌙','🌛','🌲','🌳','🌴','🌵','🌾','🌿','🍀','🍁','🍂','🍃','🌹','🌺','🌸','🌷','💐','🌱','☘️'].filter(e => e in EMOJI_GIF_MAP) },
  { name: 'Транспорт', emojis: ['🚗','🚕','🏎️','🚓','🚑','🚒','🚐','🚚','🚛','🚜','🏍️','🚲','🚀','🛸','✈️','🛩️','🚂','⛵','🚢','🚤','🚁'].filter(e => e in EMOJI_GIF_MAP) },
  { name: 'Символы', emojis: ['💯','🔴','🟠','🟡','🟢','🔵','🟣','⚫','⚪','🟤','✅','❌','🚫','🆕','🆙','🆒','🆓','🆗','⚠️','⬆️','🏁','🚩','🎌','🏴','🏳️','❗','❕','❓','❔','‼️','⁉️','🥇','🥈','🥉','🏅','🎖️','🎫','🔞','♈','♉','♊','♋','♌','♍','♎','♏','♐','♑','♒','♓','⛎'].filter(e => e in EMOJI_GIF_MAP) },
  { name: 'Прочее', emojis: ['💬','💭','🗯️','💤','♨️','🏷️','🔖','🚹','🚺','🚼','🚾','🛂','🛄','🛅','♻️','⚜️','🔱','📛','🔰','⭕','☑️','✔️','❎','➕','➖','➗','✖️','💱','💲','⚕️'].filter(e => e in EMOJI_GIF_MAP) },
];

export default EMOJI_GIF_MAP;
